name: "Test workflow"
on: 
  push:
  issues:
    types: [opened, edited, milestoned]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Print github context"
        run: |
          echo "Event is:"
          echo "${{ toJSON(github) }}"|jq .event_name
      - name: "Test step1"
        run: echo "This is step 1"
      - name: "Test step2"
        run: echo "This is step 2"
  test_job2:
    runs-on: ubuntu-latest
    steps:
      - name: "step1 in task2"
        run: echo "This is step 1"
      - name: "step2 in task2"
        run: echo "This is step 2"